# -*- coding: utf-8 -*-
"""
Flattens soccerproject-keycloak-config/soccerproject-realm.json into the handful
of facts the render harness needs, so a preview cannot disagree with the realm
it is meant to be previewing.

Why this exists: the harness used to carry a hardcoded field list, and went on
showing firstName/lastName on the register page after they had been taken out of
the realm -- a preview that lies about the one thing it is there to check.

The realm file is a keycloak-config-cli template: `$(env:NAME)` placeholders are
substituted at deploy time, so they are stubbed here before parsing.

    python3 tools/render/realm_facts.py \
        ../soccerproject-keycloak-config/soccerproject-realm.json \
        /tmp/realm.properties
"""

import io
import json
import re
import sys

# Realm flags the login/register templates branch on. Anything not in the file
# falls back to Keycloak's own default for that flag.
FLAGS = {
    'registrationAllowed': True,
    'registrationEmailAsUsername': False,
    'loginWithEmailAllowed': True,
    'resetPasswordAllowed': True,
    'rememberMe': False,
    'internationalizationEnabled': False,
    'duplicateEmailsAllowed': False,
    'editUsernameAllowed': False,
}


def load(path):
    src = io.open(path, encoding='utf-8').read()
    # Bare placeholders stand in for a whole JSON value (a list of redirect
    # URIs); quoted ones are already a valid string literal.
    return json.loads(re.sub(r'(?<!")\$\(env:[A-Z_]+\)(?!")', '"https://example.test/*"', src))


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    realm = load(sys.argv[1])
    out = {}

    for flag, default in FLAGS.items():
        out[flag] = str(bool(realm.get(flag, default))).lower()

    out['displayName'] = realm.get('displayName', '')
    out['defaultLocale'] = realm.get('defaultLocale', 'en')
    out['supportedLocales'] = ','.join(realm.get('supportedLocales', ['en']))

    # alias:providerId:displayName, in the file's own order.
    out['identityProviders'] = ','.join(
        '%s:%s:%s' % (p['alias'], p.get('providerId', p['alias']), p.get('displayName', p['alias']))
        for p in realm.get('identityProviders', []) if p.get('enabled', True)
    )

    # The register form's fields, in declared order. keycloak-config-cli only
    # applies this block when attributes.userProfileEnabled is set; without it
    # Keycloak keeps its built-in default profile (username, email, firstName,
    # lastName -- the names required), so that is what the preview must show.
    enabled = str(realm.get('attributes', {}).get('userProfileEnabled', '')).lower() == 'true'
    profile = realm.get('userProfile', {}).get('attributes') if enabled else None
    if profile is None:
        profile = [
            {'name': 'username', 'required': {}},
            {'name': 'email', 'required': {}},
            {'name': 'firstName', 'required': {}},
            {'name': 'lastName', 'required': {}},
        ]
    out['userProfileApplied'] = str(enabled).lower()
    # name:required, and `username` drops out when the email IS the username.
    email_as_username = out['registrationEmailAsUsername'] == 'true'
    out['profileAttributes'] = ','.join(
        '%s:%s' % (a['name'], 'true' if 'required' in a else 'false')
        for a in profile
        if not (email_as_username and a['name'] == 'username')
    )

    with io.open(sys.argv[2], 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('# GENERATED by tools/render/realm_facts.py -- do not edit.\n')
        for k in sorted(out):
            fh.write('%s=%s\n' % (k, out[k]))
    for k in sorted(out):
        print('%-30s %s' % (k, out[k]))


if __name__ == '__main__':
    main()
