import freemarker.template.*;
import freemarker.cache.TemplateLoader;
import java.io.*;
import java.text.MessageFormat;
import java.util.*;

/** Renders the theme's pages against a mock of the beans Keycloak 26.7.1 puts
 *  in the model, so a missing variable or a bad macro call fails here rather
 *  than on the auth host. */
public class Render {

    static Properties messages = new Properties();

    static TemplateMethodModelEx msg = args -> {
        String key = args.get(0).toString();
        String value = messages.getProperty(key, key);
        Object[] rest = new Object[Math.max(0, args.size() - 1)];
        // As Keycloak's MessageFormatterMethod: a number stays a number, so a
        // `{0,choice,...}` plural in the bundle formats here as it does there.
        for (int i = 1; i < args.size(); i++) {
            Object a = args.get(i);
            rest[i - 1] = a instanceof TemplateNumberModel n ? n.getAsNumber() : a.toString();
        }
        return new MessageFormat(value, Locale.ENGLISH).format(rest);
    };

    static TemplateMethodModelEx identity = args -> args.isEmpty() ? "" : args.get(0).toString();

    /** advancedMsg: `${key}` is a bundle lookup, anything else is a literal. */
    static TemplateMethodModelEx advancedMsg = args -> {
        if (args.isEmpty()) return "";
        String v = args.get(0).toString();
        if (v.startsWith("${") && v.endsWith("}")) {
            String key = v.substring(2, v.length() - 1);
            return messages.getProperty(key, key);
        }
        return v;
    };

    /** messagesPerField, with a configurable set of fields currently in error. */
    static Map<String, Object> perField(Set<String> errors) {
        Map<String, Object> m = new HashMap<>();
        TemplateMethodModelEx any = args -> {
            for (Object a : args) if (errors.contains(a.toString())) return true;
            return false;
        };
        m.put("existsError", any);
        m.put("exists", any);
        m.put("get", (TemplateMethodModelEx) args -> "This field is wrong.");
        m.put("getFirstError", (TemplateMethodModelEx) args -> "Invalid username or password.");
        m.put("printIfExists", (TemplateMethodModelEx) args -> "");
        return m;
    }

    static Map<String, Object> attribute(String name, String display, boolean required, String autocomplete) {
        Map<String, Object> a = new LinkedHashMap<>();
        a.put("name", name);
        a.put("displayName", display);
        a.put("required", required);
        a.put("readOnly", false);
        a.put("multivalued", false);
        a.put("value", "");
        a.put("values", new ArrayList<String>());
        a.put("autocomplete", autocomplete);
        a.put("annotations", new HashMap<String, Object>());
        a.put("html5DataAnnotations", new LinkedHashMap<String, String>());
        a.put("validators", new HashMap<String, Object>());
        a.put("group", "");
        return a;
    }

    public static void main(String[] argv) throws Exception {
        java.util.logging.Logger.getLogger("freemarker.runtime").setLevel(java.util.logging.Level.OFF);
        String themeDir = argv[0], baseDir = argv[1], propsFile = argv[2], outDir = argv[3];
        // Remaining args are message bundles, base first: later ones win, the
        // same precedence Keycloak's theme chain gives them.
        for (int i = 4; i < argv.length; i++) {
            try (Reader r = new InputStreamReader(new FileInputStream(argv[i]), "UTF-8")) {
                messages.load(r);
            }
        }
        String resourcesPath = System.getProperty("sp.resourcesPath", "/resources/x/login/soccerproject");
        // The realm the preview is of. Generated by tools/render/realm_facts.py
        // from soccerproject-keycloak-config/soccerproject-realm.json -- never a
        // list hardcoded here, or the preview drifts from the realm silently.
        Properties realmFacts = new Properties();
        String factsPath = System.getProperty("sp.realmFacts");
        if (factsPath != null) {
            try (Reader r = new InputStreamReader(new FileInputStream(factsPath), "UTF-8")) {
                realmFacts.load(r);
            }
        }

        Properties themeProps = new Properties();
        try (Reader r = new InputStreamReader(new FileInputStream(propsFile), "UTF-8")) {
            themeProps.load(r);
        }

        Configuration cfg = new Configuration(Configuration.VERSION_2_3_34);
        cfg.setTemplateLoader(new freemarker.cache.MultiTemplateLoader(new TemplateLoader[]{
            new freemarker.cache.FileTemplateLoader(new File(themeDir)),
            new freemarker.cache.FileTemplateLoader(new File(baseDir))}));
        cfg.setDefaultEncoding("UTF-8");
        cfg.setOutputFormat(freemarker.core.HTMLOutputFormat.INSTANCE);
        // Keycloak fails loudly on an undefined variable too; keep it strict so
        // a typo in a bean name is an error here, not a blank on the page.
        cfg.setTemplateExceptionHandler(TemplateExceptionHandler.RETHROW_HANDLER);

        Map<String, Object> props = new HashMap<>();
        for (String k : themeProps.stringPropertyNames()) props.put(k, themeProps.getProperty(k));

        Map<String, Object> realm = new HashMap<>();
        realm.put("password", true);
        for (String flag : new String[]{"internationalizationEnabled", "registrationAllowed",
                "resetPasswordAllowed", "rememberMe", "loginWithEmailAllowed",
                "registrationEmailAsUsername", "editUsernameAllowed"}) {
            realm.put(flag, Boolean.parseBoolean(realmFacts.getProperty(flag, "false")));
        }
        realm.put("displayName", realmFacts.getProperty("displayName", "SoccerProject"));
        realm.put("duplicateEmailsAllowed", false);
        realm.put("editUsernameAllowed", false);
        realm.put("loginWithEmailAllowed", true);
        realm.put("resetPasswordAllowed", true);
        realm.put("name", "soccerproject");
        realm.put("displayNameHtml", "SoccerProject");

        List<Map<String, Object>> supported = new ArrayList<>();
        // The realm's list, not the theme's: Keycloak renders the picker from the
        // realm, and the two disagreeing is itself a thing worth seeing.
        for (String code : realmFacts.getProperty("supportedLocales",
                themeProps.getProperty("locales", "en")).split(",")) {
            Map<String, Object> l = new HashMap<>();
            l.put("languageTag", code);
            l.put("label", code.toUpperCase());
            l.put("url", "?ui_locales=" + code);
            supported.add(l);
        }
        Map<String, Object> locale = new HashMap<>();
        locale.put("currentLanguageTag", realmFacts.getProperty("defaultLocale", "en"));
        locale.put("supported", supported);
        locale.put("rtl", false);

        Map<String, Object> url = new HashMap<>();
        for (String k : new String[]{"loginAction", "loginResetCredentialsUrl", "registrationUrl",
                "loginRestartFlowUrl", "loginUrl", "registrationAction", "oauthAction"}) {
            url.put(k, "/realms/soccerproject/" + k);
        }
        // -Dsp.loginRestartUrl=https://auth.development.soccerproject.com/x previews the
        // host-derived site links (template.ftl spSite); unset keeps the relative mock.
        url.put("loginRestartFlowUrl",
                System.getProperty("sp.loginRestartUrl", "/realms/soccerproject/loginRestartFlowUrl"));
        url.put("resourcesPath", resourcesPath);

        Map<String, Object> auth = new HashMap<>();
        auth.put("showUsername", (TemplateMethodModelEx) a -> false);
        auth.put("showResetCredentials", (TemplateMethodModelEx) a -> false);
        auth.put("showTryAnotherWayLink", (TemplateMethodModelEx) a -> true);
        auth.put("selectedCredential", "");
        auth.put("attemptedUsername", "manager@example.com");
        auth.put("authenticationSelections", List.of(
            Map.of("authExecId", "1", "iconCssClass", "kcAuthenticatorPasswordClass",
                   "displayName", "password", "helpText", "password-help-text"),
            Map.of("authExecId", "2", "iconCssClass", "kcAuthenticatorOTPClass",
                   "displayName", "otp", "helpText", "otp-help-text")));

        List<Map<String, Object>> providers = new ArrayList<>();
        String idps = realmFacts.getProperty("identityProviders", "");
        for (String entry : idps.isEmpty() ? new String[0] : idps.split(",")) {
            String[] p = entry.split(":", 3);   // alias:providerId:displayName
            Map<String, Object> m = new HashMap<>();
            m.put("alias", p[0]);
            m.put("providerId", p.length > 1 ? p[1] : p[0]);
            m.put("displayName", p.length > 2 ? p[2] : p[0]);
            m.put("loginUrl", "/broker/" + p[0] + "/login");
            m.put("iconClasses", "");
            providers.add(m);
        }
        Map<String, Object> social = new HashMap<>();
        social.put("providers", providers);

        Map<String, Object> profile = new HashMap<>();
        // The realm's declared user profile, in its own order, with its own
        // required-ness -- realm_facts.py already resolved whether the block is
        // actually applied (attributes.userProfileEnabled) and dropped
        // `username` when the email is the username.
        List<Map<String, Object>> attrs = new ArrayList<>();
        String profileAttrs = realmFacts.getProperty("profileAttributes", "email:true");
        for (String entry : profileAttrs.split(",")) {
            String[] a = entry.split(":", 2);   // name:required
            attrs.add(attribute(a[0], "${" + a[0] + "}",
                a.length > 1 && Boolean.parseBoolean(a[1]),
                "email".equals(a[0]) ? "email" : ("username".equals(a[0]) ? "username" : null)));
        }
        profile.put("attributes", attrs);
        profile.put("html5DataAnnotations", new LinkedHashMap<String, String>());

        Map<String, Object> base = new HashMap<>();
        base.put("properties", props);
        base.put("realm", realm);
        base.put("locale", locale);
        base.put("url", url);
        base.put("auth", auth);
        base.put("social", social);
        base.put("profile", profile);
        base.put("msg", msg);
        base.put("advancedMsg", advancedMsg);
        base.put("kcSanitize", identity);
        base.put("login", new HashMap<String, Object>());
        base.put("passwordRequired", true);
        base.put("scripts", new ArrayList<String>());

        int failures = 0;
        // name -> (label, extra model)
        List<Object[]> cases = new ArrayList<>();
        Map<String, Object> quietAuth = new HashMap<>(auth);
        quietAuth.put("showTryAnotherWayLink", (TemplateMethodModelEx) x -> false);
        cases.add(new Object[]{"login.ftl", "login-clean",
            Map.of("auth", quietAuth, "message", Map.of()), Collections.<String>emptySet()});
        cases.add(new Object[]{"login.ftl", "login-with-info",
            Collections.emptyMap(), Collections.<String>emptySet()});
        cases.add(new Object[]{"login.ftl", "login-error",
            Map.of("message", Map.of("type", "error", "summary", "Invalid username or password.")),
            Set.of("username", "password")});
        cases.add(new Object[]{"login.ftl", "login-no-social",
            Map.of("social", Map.of("providers", new ArrayList<>())), Collections.<String>emptySet()});
        cases.add(new Object[]{"login.ftl", "login-attempted-username",
            Map.of("auth", withUsername(auth)), Collections.<String>emptySet()});
        Map<String, Object> hintProfile = new HashMap<>(profile);
        List<Map<String, Object>> hinted = new ArrayList<>();
        for (Map<String, Object> a : (List<Map<String, Object>>) profile.get("attributes")) {
            Map<String, Object> c = new HashMap<>(a);
            if ("username".equals(c.get("name"))) c.put("value", "manager@example.com");
            hinted.add(c);
        }
        hintProfile.put("attributes", hinted);
        cases.add(new Object[]{"register.ftl", "register-login-hint",
            Map.of("auth", quietAuth, "message", Map.of(), "profile", hintProfile),
            Collections.<String>emptySet()});
        // The same prefill, but redisplayed after a failed post: the values are
        // the visitor's own now and the move must not fire.
        cases.add(new Object[]{"register.ftl", "register-login-hint-redisplay",
            Map.of("auth", quietAuth, "profile", hintProfile,
                   "message", Map.of("type", "error", "summary", "Please check your details.")),
            Set.of("email")});
        // A login_hint that is a handle, not an address: it must stay in Username.
        List<Map<String, Object>> handled = new ArrayList<>();
        for (Map<String, Object> a : (List<Map<String, Object>>) profile.get("attributes")) {
            Map<String, Object> c = new HashMap<>(a);
            if ("username".equals(c.get("name"))) c.put("value", "Tomtoch");
            handled.add(c);
        }
        Map<String, Object> handleProfile = new HashMap<>(profile);
        handleProfile.put("attributes", handled);
        cases.add(new Object[]{"register.ftl", "register-login-hint-handle",
            Map.of("auth", quietAuth, "message", Map.of(), "profile", handleProfile),
            Collections.<String>emptySet()});
        cases.add(new Object[]{"register.ftl", "register-clean",
            Map.of("auth", quietAuth, "message", Map.of()), Collections.<String>emptySet()});
        cases.add(new Object[]{"register.ftl", "register-error",
            Map.of("message", Map.of("type", "error", "summary", "Please check your details.")),
            Set.of("global", "email", "password", "password-confirm")});
        cases.add(new Object[]{"register.ftl", "register-no-social",
            Map.of("social", Map.of("providers", new ArrayList<>())), Collections.<String>emptySet()});
        cases.add(new Object[]{"register.ftl", "register-terms",
            Map.of("termsAcceptanceRequired", true), Collections.<String>emptySet()});
        // Inherited pages: rendered through OUR template.ftl with the base body.
        for (String n : new String[]{"login-reset-password.ftl", "login-update-password.ftl",
                "login-otp.ftl", "terms.ftl", "info.ftl", "error.ftl", "login-verify-email.ftl",
                "select-authenticator.ftl", "login-page-expired.ftl", "login-update-profile.ftl"}) {
            cases.add(new Object[]{n, "inherited-" + n.replace(".ftl", ""), Collections.emptyMap(), Collections.<String>emptySet()});
        }

        new File(outDir).mkdirs();
        for (Object[] c : cases) {
            String tpl = (String) c[0], label = (String) c[1];
            @SuppressWarnings("unchecked") Map<String, Object> extra = (Map<String, Object>) c[2];
            @SuppressWarnings("unchecked") Set<String> errs = (Set<String>) c[3];
            Map<String, Object> model = new HashMap<>(base);
            model.put("messagesPerField", perField(errs));
            model.putAll(extra);
            // Beans the info/error/expired pages need.
            model.putIfAbsent("message", Map.of("type", "info", "summary", "Something to tell you."));
            model.put("messageHeader", null);
            model.put("pageRedirectUri", "/after");
            model.put("actionUri", "/action");
            model.put("client", Map.of("baseUrl", "/", "attributes", Map.of()));
            model.put("skipLink", false);
            model.put("otpLogin", Map.of("userOtpCredentials", new ArrayList<>()));
            model.put("username", "manager@example.com");
            model.put("verifyEmail", true);
            model.put("stateChecker", "x");
            model.put("isAppInitiatedAction", false);
            // KC's PasswordPoliciesBean. An unset rule is null there, so absent here.
            model.put("passwordPolicies", Map.of("length", 8, "upperCase", 1, "digits", 1,
                    "notUsername", true, "notEmail", false));
            model.put("pageId", tpl.replace(".ftl", ""));
            model.put("otpLogin", Map.of("userOtpCredentials", new ArrayList<>()));
            model.put("selectedCredential", "");
            model.put("recoveryAuthnCodesConfigBean", Map.of("generatedRecoveryAuthnCodesList", new ArrayList<>()));
            model.put("logoutConfirm", Map.of("code", "x", "skipLink", false));
            model.put("triggered_from_display_unsupported", false);
            try {
                StringWriter w = new StringWriter();
                cfg.getTemplate(tpl).process(model, w);
                String html = w.toString();
                try (Writer f = new OutputStreamWriter(new FileOutputStream(new File(outDir, label + ".html")), "UTF-8")) {
                    f.write(html);
                }
                System.out.printf("OK    %-34s %6d bytes%n", label, html.length());
            } catch (Exception e) {
                failures++;
                String m = e.getMessage();
                System.out.printf("FAIL  %-34s %s%n", label, m == null ? e.toString() : m.split("\n")[0]);
            }
        }
        System.out.println(failures == 0 ? "\nall rendered" : "\n" + failures + " failed");
        System.exit(failures == 0 ? 0 : 1);
    }

    static Map<String, Object> withUsername(Map<String, Object> auth) {
        Map<String, Object> a = new HashMap<>(auth);
        a.put("showUsername", (TemplateMethodModelEx) x -> true);
        return a;
    }
}
